name: Deploy to app01
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - run: curl -H X-Api-Key:${{ secrets.APP01_API_KEY }} https://app01.lineageos.org/deploy/issue_bot/${{ github.sha }}
